name: Helm lint, test, package and publish

on:
  push:
    branches: ["master"]

jobs:
  helm-suite:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Helm Artifactory Publisher
      uses: mbovo/action-helm-artifactory@v1.0.0

      with:
        action: "push"
      env:
        ACTION: push
        CHART_DIR: .
        ARTIFACTORY_URL: https://splitio.jfrog.io/artifactory/helm/
        ARTIFACTORY_USERNAME: ${{ secrets.ARTIFACTORY_DOCKER_USER }}
        ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_DOCKER_PASS }}
